---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"
  # this will only update values.yaml within the chart
  - package-ecosystem: docker
    directories:
      - "/charts/**"
    schedule:
      interval: weekly
