namespace:
  create: false
  name: ctlog-system

imagePullSecrets: []

server:
  replicaCount: 1
  config:
    key: treeID
    treeID: ""
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/ct_server
    pullPolicy: IfNotPresent
    version: v0.7.25@sha256:ba7e3303cae06097fab776e5b45e9ff8aa32ebe05ca472c63ef6e62156e69717
  livenessProbe:
    httpGet:
      path: /healthz
      port: 6962
    initialDelaySeconds: 10
  readinessProbe:
    httpGet:
      path: /healthz
      port: 6962
    initialDelaySeconds: 10
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: false
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "6963"
  portHTTP: 6962
  portHTTPMetrics: 6963
  service:
#    backendConfig:
#      name: ctlog-backend-config
#      spec: # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#configuring_ingress_features_through_backendconfig_parameters
#        securityPolicy:
#          name: ctlog-security-policy
#        logging:
#          enable: true
#        healthCheck:
#          port: 6962
#          requestPath: "/healthz"
#          type: HTTP
    type: ClusterIP
    ports:
      - name: 6962-tcp
        port: 80
        protocol: TCP
        targetPort: 6962
      - name: 6963-tcp
        port: 6963
        protocol: TCP
        targetPort: 6963
  ingress:
    enabled: false
    className: nginx
    hosts:
      - path: /
    annotations: {}
    tls: []
  ingresses:
    - enabled: false
      name: "gce-ingress"
      className: "gce"
      hosts:
        - host: fulcio.localhost
          paths:
            - path: /test
              pathType: Prefix
            - path: /other-shard
              serviceName: other-shard
      annotations: {}
      tls: []
      staticGlobalIP: lb-ext-ip
      frontendConfigSpec:   # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#configuring_ingress_features_through_frontendconfig_parameters
        sslPolicy: ctlog-ssl-policy
        redirectToHttps:
          enabled: true
  extraArgs: []
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  tolerations: []
  nodeSelector: {}
  affinity: {}

createtree:
  enabled: true
  name: createtree
  # This must be < 20 characters
  displayName: ctlog-tree
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    pullPolicy: IfNotPresent
    version: v0.7.25@sha256:8dee13f41c0918156ee3b530374e8d6ee790742c4e7143eddfd323d5c0fb4a7f
  ttlSecondsAfterFinished: 3600
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  annotations: {}
  tolerations: []
  nodeSelector: {}
  affinity: {}

createctconfig:
  enabled: true
  replicaCount: 1
  backoffLimit: 6
  name: createctconfig
  initContainerImage:
    curl:
      registry: docker.io
      repository: curlimages/curl
      version: 8.16.0@sha256:463eaf6072688fe96ac64fa623fe73e1dbe25d8ad6c34404a669ad3ce1f104b6
      imagePullPolicy: IfNotPresent
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createctconfig
    pullPolicy: IfNotPresent
    version: v0.7.25@sha256:fee343269ad0bdb91e0a22196b6ed2a31d8b6ca3ea8ea18147fa6a83368345ff
  fulcioURL: "http://fulcio-server.fulcio-system.svc"
  logPrefix: sigstorescaffolding
  privateKeyPasswordSecretName: ""
  ttlSecondsAfterFinished: 3600
  pubkeysecret: "ctlog-public-key"
  # If there's an existing private key that should be used for ctlog, specify
  # here. This is important if a key has been created and imported into TUF.
  privateSecret: ""
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  annotations: {}
  tolerations: []
  nodeSelector: {}
  affinity: {}

trillian:
  namespace: trillian-system
  logServer:
    name: trillian-logserver
    portRPC: 8091

# Force namespace of namespaced resources
forceNamespace: ""
