apiVersion: v2
name: rekor-tiles
description: Part of the sigstore project, Rekor v2 (Rekor on tiles) is a signature transparency log
type: application
version: 0.2.19
appVersion: "2.0.0"
keywords:
  - security
  - transparency logs
home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/rekor-tiles
maintainers:
  - name: The Sigstore Authors
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: rekor-tiles
      image: ghcr.io/sigstore/rekor-tiles:v2.0.0-rc2@sha256:373fc569fc26e5e68710df958128f5d67e0c3a59a851913069bcf94ca0569d32
