apiVersion: v2
name: updatetree
description: Update the status of an existing Trillian tree

type: application

version: 0.0.8
appVersion: 0.6.16


keywords:
  - security
  - trillian
  - updatetree

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: updatetree
      image: ghcr.io/sigstore/scaffolding/updatetree:v0.6.16@sha256:228756bc47ebc1eabe8a889484a5443f936817ae591afee9b1712f5219323628
