apiVersion: v2
name: updatetree
description: Update the status of an existing Trillian tree

type: application

version: 0.0.12
appVersion: 0.7.5


keywords:
  - security
  - trillian
  - updatetree

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: updatetree
      image: ghcr.io/sigstore/scaffolding/updatetree:v0.7.5@sha256:6931d76881035a6451353568eb5c29764cf81c3e71dc5cb512e8cd18b2b89983
