apiVersion: v2
name: fulcio
description: Fulcio

type: application

version: 0.4.10
appVersion: 0.5.3

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: ctlog
    version: 0.2.24
    repository: https://sigstore.github.io/helm-charts
    condition: ctlog.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: fulcio
      image: gcr.io/projectsigstore/fulcio@sha256:61081295a8f75ed7537b5d1f8c7320e078dc00e4562c0bf605fbefa062c690de
    - name: createcerts
      image: ghcr.io/sigstore/scaffolding/createcerts@sha256:73e7ac35d0e5169bd14a5cb6caed2e7d44277dec3d1de92e08f4d055523089a1
