namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/prober:v0.7.16@sha256:5d1e8f292251e319564331cbec242a24193e330c58d7e2ce75096beec9d16a8b
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  args:
    fulcioHost: https://fulcio.sigstore.dev
    fulcioGrpcHost: fulcio.sigstore.dev
    rekorHost: https://rekor.sigstore.dev
    frequency: 10
    writeProber: false
    rekorRequests: []
    fulcioRequests: []
    trustRekorAPIPublicKey: false
prometheus:
  port: 8080
tolerations: []
nodeSelector: {}
affinity: {}
