namespace:
  create: false
  name: rekor-system
imagePullSecrets: []

initContainerImage:
  curl:
    registry: docker.io
    repository: curlimages/curl
    # -- 8.4.0
    version: "sha256:4a3396ae573c44932d06ba33f8696db4429c419da87cbdc82965ee96a37dd0af"
    imagePullPolicy: IfNotPresent

redis:
  enabled: true
  replicaCount: 1
  hostname: ""
  port: 6379
  args:
    - --bind
    - 0.0.0.0
    - --appendonly
    - "yes"
  name: redis
  image:
    registry: docker.io
    repository: redis
    pullPolicy: IfNotPresent
    # -- 6.2.14-alpine3.18
    version: "sha256:452b7655bda0e270a6376b71d22fcb30662e745dcb4728f99fa87f01287b465d"
  resources: {}
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /bin/sh
        - -i
        - -c
        - test "$(redis-cli -h 127.0.0.1 ping)" = "PONG"
  service:
    type: ClusterIP
    ports:
      - name: 6379-tcp
        port: 6379
        protocol: TCP
        targetPort: 6379
  serviceAccount:
    create: true
    name: ""
    annotations: {}

server:
  enabled: true
  replicaCount: 1
  name: server
  port: 3000
  image:
    registry: gcr.io
    repository: projectsigstore/rekor-server
    pullPolicy: IfNotPresent
    # crane digest gcr.io/projectsigstore/rekor-server:v1.3.4
    version: "sha256:bafe388dd66097f06516bc67cf9c0fc5da629798f60a2326e8c4b4584c82ed4f"
  logging:
    production: false
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - path: /
        host: root
    annotations: {}
    tls: []
  ingresses:
    - enabled: false
      name: "gce-ingress"
      className: "gce"
      hosts:
        - path: /
          host: root
      annotations: {}
      tls: []
      staticGlobalIP: lb-ext-ip
      frontendConfigSpec:   # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#configuring_ingress_features_through_frontendconfig_parameters
        sslPolicy: rekor-ssl-policy
        redirectToHttps:
          enabled: true
      backendConfigSpec:   # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#configuring_ingress_features_through_backendconfig_parameters
        securityPolicy:
          name: rekor-security-policy
        logging:
          enable: true
  service:
    type: ClusterIP
    ports:
      - name: 3000-tcp
        port: 80
        protocol: TCP
        targetPort: 3000
      - name: 2112-tcp
        port: 2112
        protocol: TCP
        targetPort: 2112
  signer: memory
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    httpGet:
      port: 3000
      path: /ping
  sharding:
    mountPath: /sharding
    filename: sharding-config.yaml
    contents: ""
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    httpGet:
      port: 3000
      path: /ping
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  config:
    key: treeID
    treeID: ""
  retrieve_api:
    enabled: true
  attestation_storage:
    enabled: true
    bucket: file:///var/run/attestations
    persistence:
      enabled: true
      annotations: {}
      storageClass: ""
      size: 5Gi
      mountPath: /var/lib/mysql
      subPath: ""
      existingClaim: ""
      accessModes:
        - ReadWriteOnce
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "2112"
  resources: {}
  extraArgs: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}
createtree:
  name: createtree
  force: false
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    pullPolicy: IfNotPresent
    # v0.6.10
    version: "sha256:1c8c06786a981344b5643443a4f62580e36a49e02f08783511a2766d5e0081ad"
  ttlSecondsAfterFinished: 3600
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  resources: {}
  annotations: {}
# Configure backfillredis to repair indices that were not inserted into Redis.
backfillredis:
  name: backfillredis
  enabled: false
  image:
    registry: ghcr.io
    repository: sigstore/rekor/backfill-redis
    pullPolicy: IfNotPresent
    # v1.3.4
    version: "sha256:21a9b240cb5e30f04b701b72e67554d0d1904f96a42ef361f1bde3e57274d05e"
  ttlSecondsAfterFinished: 3600
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  rekorAddress: rekor.rekor-system.svc
  startIndex: -1
  endIndex: -1
  resources: {}

# Configure Trillian dependency
trillian:
  enabled: true
  namespace:
    name: trillian-system
    create: true
  forceNamespace: trillian-system
  fullnameOverride: trillian
  adminServer: ""
  logServer:
    name: trillian-logserver
    fullnameOverride: trillian-logserver
    portHTTP: 8090
    portRPC: 8091
  logSigner:
    name: trillian-logsigner
    fullnameOverride: trillian-logsigner
  mysql:
    fullnameOverride: trillian-mysql

# Force namespace of namespaced resources
forceNamespace: ""
