{{- if eq .Values.server.ingress.className "gce" }}
{{- if .Values.server.ingress.http.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: fulcio-http-gce-frontend-config
{{ include "fulcio.namespace" . | indent 2 }}
  labels:
    {{- include "fulcio.labels" . | nindent 4 }}
spec:
  sslPolicy: {{ .Values.server.ingress.http.sslPolicy | quote }} # note this is defined in terraform
  redirectToHttps:
    enabled: {{ .Values.server.ingress.http.httpsRedirect }}
---
{{- end }}
{{- if .Values.server.ingress.grpc.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: fulcio-grpc-gce-frontend-config
{{ include "fulcio.namespace" . | indent 2 }}
  labels:
    {{- include "fulcio.labels" . | nindent 4 }}
spec:
  sslPolicy: {{ .Values.server.ingress.grpc.sslPolicy | quote }} # note this is defined in terraform
  redirectToHttps:
    enabled: {{ .Values.server.ingress.grpc.httpsRedirect }}
{{- end }}
{{- end }}