apiVersion: v2
name: trillian
description: |
  Trillian is a log that stores an accurate, immutable and verifiable history of activity.

type: application

version: 0.3.13
appVersion: 1.7.2

keywords:
  - security
  - pki

home: https://sigstore.dev/
sources:
  - https://github.com/google/trillian
  - https://github.com/sigstore/helm-charts/tree/main/charts/trillian

maintainers:
  - name: The Sigstore Authors
    url: https://sigstore.dev/

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: curl
      image: docker.io/curlimages/curl:8.16.0@sha256:463eaf6072688fe96ac64fa623fe73e1dbe25d8ad6c34404a669ad3ce1f104b6
    - name: netcat
      image: docker.io/subfuzion/netcat@sha256:7e808e84a631d9c2cd5a04f6a084f925ea388e3127553461536c1248c3333c8a
    - name: db_server
      image: gcr.io/trillian-opensource-ci/db_server:v1.5.3@sha256:2a685a38dd0129cceb646c232d285383f614c7e6fa51ff8f512aef78e4298461
    - name: log_server
      image: ghcr.io/sigstore/scaffolding/trillian_log_server:v1.7.2@sha256:2c677cab8e4fd9d5d71dc55db574caed93a3896ee8229e50a95c8d09625866db
    - name: log_signer
      image: ghcr.io/sigstore/scaffolding/trillian_log_signer:v1.7.2@sha256:65ed1871a11d4bf2c1d0b7c1f8b5fbc90f842788edc577b90adb024dec03dbe2
    - name: cloud_proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.18.2-alpine@sha256:12fc14dd5bf90f69ed370a5990aff6f18a05d7b427465c621042bc1e2fac662f
    - name: scaffold_cloud_proxy
      image: ghcr.io/sigstore/scaffolding/cloudsqlproxy:v0.7.25@sha256:e3963d9afdc8c5eb76573347b1d66895300cdfd065894844b7ba5cbefbb9083b
    - name: createdb
      image: ghcr.io/sigstore/scaffolding/createdb:v0.7.25@sha256:472c5271ad75454a18a561bd085f44e6b6b21e7fb5413343e7c69b63d6d13622
