namespace:
  create: false
  name: trillian-system
initContainerImage:
  curl:
    registry: mirror.gcr.io
    repository: curlimages/curl
    # 7.83.1
    version: "sha256:e83fef2d5a036d40df4ded829141e8c0ec41871490d252fb8c81cb4580ebb35b"
    imagePullPolicy: IfNotPresent
  netcat:
    registry: mirror.gcr.io
    repository: toolbelt/netcat
    # 2022-05-23
    version: "sha256:7d921b6d368fb1736cb0832c6f57e426c161593c075847af3378eb3185801cea"
    imagePullPolicy: IfNotPresent

mysql:
  gcp:
    enabled: false
    instance: ""
    cloudsql:
      registry: gcr.io
      repository: cloudsql-docker/gce-proxy
      version: "1.29.0"
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
          - all
  enabled: true
  replicaCount: 1
  name: mysql
  hostname: ""
  port: 3306
  strategy:
    type: Recreate
  image:
    registry: gcr.io
    repository: trillian-opensource-ci/db_server
    pullPolicy: IfNotPresent
    # v1.4.1
    version: "sha256:ae4043e9c5e4de522fb4958e92d592aa97c7fc294a12849b902fd1facd7122c6"
  resources: {}
  args:
    - "--ignore-db-dir=lost+found"
  service:
    type: ClusterIP
    ports:
      - name: 3306-tcp
        port: 3306
        protocol: TCP
        targetPort: 3306
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /etc/init.d/mysql
        - status
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /etc/init.d/mysql
        - status
  secret:
    annotations: {}
  auth:
    username: "mysql"
    password: ""
    rootPassword: ""
    existingSecret: ""
  persistence:
    enabled: true
    annotations: {}
    storageClass: null
    size: 5Gi
    mountPath: /var/lib/mysql
    subPath: ""
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
  serviceAccount:
    create: true
    name: ""
    annotations: {}
logServer:
  enabled: true
  replicaCount: 1
  name: log-server
  portRPC: 8091
  portHTTP: 8090
  image:
    registry: gcr.io
    repository: projectsigstore/trillian_log_server
    pullPolicy: IfNotPresent
    # v0.7.0
    version: "sha256:4599a3f037234423d13ff84755679a56da62363e7ed07c70bc556078fd73986d"
  service:
    type: ClusterIP
    ports:
      - name: 8091-tcp
        port: 8091
        protocol: TCP
        targetPort: 8091
      - name: 8090-tcp
        port: 8090
        protocol: TCP
        targetPort: 8090
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  extraArgs: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}
logSigner:
  enabled: true
  replicaCount: 1
  name: log-signer
  forceMaster: true
  portRPC: 8091
  portHTTP: 8090
  image:
    registry: gcr.io
    repository: projectsigstore/trillian_log_signer
    pullPolicy: IfNotPresent
    # v0.7.0
    version: "sha256:87699af429d79440f7e0a487d215c2129bf97b37698370d050a68822996f93f0"
  service:
    type: ClusterIP
    ports:
      - name: 8091-tcp
        port: 8091
        protocol: TCP
        targetPort: 8091
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  extraArgs: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}
# Force namespace of namespaced resources
forceNamespace: ""
