namespace:
  create: false
  name: trillian-system

imagePullSecrets: []

initContainerImage:
  curl:
    registry: docker.io
    repository: curlimages/curl
    # -- 8.5.0
    version: sha256:4bfa3e2c0164fb103fb9bfd4dc956facce32b6c5d47cc09fcec883ce9535d5ac
    imagePullPolicy: IfNotPresent
  netcat:
    registry: cgr.dev
    repository: chainguard/netcat
    # -- 2023-06-13
    version: "sha256:7243b469d34bd28969fa2c764a12d91084c427209540bb68645629d635b3f143"
    imagePullPolicy: IfNotPresent

storageSystem:
  driver: mysql
  envCredentials: null
quotaSystem:
  driver: mysql

mysql:
  gcp:
    enabled: false
    instance: ""
    scaffoldSQLProxy:
      registry: ghcr.io
      repository: sigstore/scaffolding/cloudsqlproxy
      # -- v0.7.5 which is based on cloud-sql-proxy:2.12.0-alpine
      version: sha256:3dfbca0320a497cddd66a748b53377982c6309cb9e3c73f21d2b1bdef14730ba
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
    cloudsql:
      registry: gcr.io
      repository: cloud-sql-connectors/cloud-sql-proxy:2.12.0-alpine
      # -- crane digest gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.12.0-alpine
      version: sha256:a3843521730914f074f364c5bec608319ebeb5e66da9314ba45b16cd8223547f
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      unixDomainSocket:
        enabled: false
        path: /cloudsql
  enabled: true
  replicaCount: 1
  name: mysql
  hostname: ""
  port: 3306
  strategy:
    type: Recreate
  image:
    registry: gcr.io
    repository: trillian-opensource-ci/db_server
    pullPolicy: IfNotPresent
    # -- crane digest gcr.io/trillian-opensource-ci/db_server:v1.5.3
    version: sha256:2a685a38dd0129cceb646c232d285383f614c7e6fa51ff8f512aef78e4298461
  resources: {}
  args:
    - "--ignore-db-dir=lost+found"
  service:
    type: ClusterIP
    ports:
      - name: 3306-tcp
        port: 3306
        protocol: TCP
        targetPort: 3306
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /etc/init.d/mysql
        - status
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /etc/init.d/mysql
        - status
  secret:
    annotations: {}
  auth:
    username: "mysql"
    password: ""
    rootPassword: ""
    existingSecret: ""
  persistence:
    enabled: true
    annotations: {}
    storageClass: null
    size: 5Gi
    mountPath: /var/lib/mysql
    subPath: ""
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
  serviceAccount:
    create: true
    name: ""
    annotations: {}

logServer:
  enabled: true
  replicaCount: 1
  name: log-server
  portRPC: 8091
  portHTTP: 8090
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/trillian_log_server
    pullPolicy: IfNotPresent
    # -- v0.7.5
    version: sha256:9da02afc1d475125a2205bc1a862e3f041db2ce7aec603e22d59f97e4f5845a3
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    ports:
      - name: 8091-tcp
        port: 8091
        protocol: TCP
        targetPort: 8091
      - name: 8090-tcp
        port: 8090
        protocol: TCP
        targetPort: 8090
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  extraArgs: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}

logSigner:
  enabled: true
  replicaCount: 1
  name: log-signer
  forceMaster: true
  portRPC: 8091
  portHTTP: 8090
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/trillian_log_signer
    pullPolicy: IfNotPresent
    # -- v0.7.5
    version: sha256:99262641e4187f7496c033c5d407e0df4356d22ab646b44105674df9a5ca63cc
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    ports:
      - name: 8091-tcp
        port: 8091
        protocol: TCP
        targetPort: 8091
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  extraArgs: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}

createdb:
  enabled: true
  dbname: trillian
  ttlSecondsAfterFinished: 3600
  name: createdb
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createdb
    pullPolicy: IfNotPresent
    # -- v0.7.5
    version: sha256:108dcdb64cff7520574f1efd63ebba71d7d4ea60fe652b0ef2b5f60ccd596042
  serviceAccount:
    create: false
    name: ""
    annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Force namespace of namespaced resources
forceNamespace: ""
