{{- if .Values.server.ingress.enabled }}
{{- if eq .Values.server.ingress.className "gce" }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: rekor-gce-backend-config
  labels:
    {{- include "rekor.labels" . | nindent 4 }}
{{ include "rekor.namespace" . | indent 2 }}
spec:
  securityPolicy:
    name: {{ .Values.server.service.securityPolicy | quote }} # note this is where rate-limiting is configured, and is defined in terraform
  logging:
    enable: {{ .Values.server.service.logging }}
    {{- if .Values.server.service.loggingSampleRate }}
    sampleRate: {{ .Values.server.service.loggingSampleRate }}
    {{- end }}
{{- end }}
{{- end }}

