{{- if .Values.server.ingress.enabled }}
{{- if eq .Values.server.ingress.className "gce" }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: rekor-gce-frontend-config
{{ include "rekor.namespace" . | indent 2 }}
  labels:
    {{- include "rekor.labels" . | nindent 4 }}
spec:
  sslPolicy: {{ .Values.server.ingress.sslPolicy }} # note this is defined in terraform
  redirectToHttps:
    enabled: {{ .Values.server.ingress.httpsRedirect }}
{{ end }}
{{ end }}
